server:
  port: 8010
spring:
  application:
    name: gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
zuul:
  prefix: /api
  routes:
      item-service: /item/**